name: Release

on:
  push:
    branches:
      - "main"

jobs:
  
  build-mac:
    permissions:
      contents: write
    name: MacOS Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Cargo
      uses: actions-rs/cargo@v1
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Yarn
      run: npm install --location=global yarn
    - name: Install Dependencies
      run: yarn install
    - name: Build MacOS Bundles
      run: yarn build

  build-linux:
    permissions:
      contents: write
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Cargo
      uses: actions-rs/cargo@v1
    - name: Install Dependencies
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: Build Linux Bundles
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build

  build-windows:
    permissions:
      contents: write
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Cargo
      uses: actions-rs/cargo@v1
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Yarn
      run: npm install --location=global yarn
    - name: Install Dependencies
      run: yarn install
    - name: Build Windows Bundles
      run: yarn build
