name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-mac:
    name: MacOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install --location=global yarn
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      - name: Build MacOS Bundles
        run: yarn build
      - name: Save Bundles
        uses: actions/upload-artifact@v3
        with:
          name: mac-bundles
          path: |
            ./src-tauri/target/release/bundle/macos/Typino.app
            ./src-tauri/target/release/bundle/dmg/Typino*.dmg

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Package repository
        run: sudo apt-get update
      - name: Install Tauri Dependencies
        run: sudo apt-get install -y
          libwebkit2gtk-4.0-dev
          build-essential
          curl
          wget
          libssl-dev
          libgtk-3-dev
          libayatana-appindicator3-dev
          librsvg2-dev
      - name: Install rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install --location=global yarn
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      - name: Build Linux Bundles
        run: yarn build
      - name: Save Bundles
        uses: actions/upload-artifact@v3
        with:
          name: linux-bundles
          path: |
            ./src-tauri/target/release/bundle/deb/typino*.deb
            ./src-tauri/target/release/bundle/appimage/typino*.AppImage

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Cargo
        uses: actions-rs/cargo@v1
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install --location=global yarn
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      - name: Build Windows Bundles
        run: yarn build
      - name: Save Bundles
        uses: actions/upload-artifact@v3
        with:
          name: windows-bundles
          path: |
            ./src-tauri/target/release/bundle/msi/Typino*.msi

  release:
    name: Create a Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Create a Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.prop }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md

  release-assets-mac:
    name: Upload MacOS Bundles
    needs:
      - build-mac
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Download Bundles
        uses: actions/download-artifact@v3
        with:
          name: mac-bundles
          path: ./bundle
      - name: Upload Typino.app
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ jobs.release.outputs.upload_url }}
          asset_path: ./bundle/macos/Typino.app
          asset_name: Typino-${{ steps.version.outputs.prop }}.app
          asset_content_type: application/gzip
      - name: Upload Typino.dmg
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ jobs.release.outputs.upload_url }}
          asset_path: ./bundle/dmg/Typino*.dmg
          asset_name: Typino-${{ steps.version.outputs.prop }}.dmg
          asset_content_type: application/gzip

  release-assets-linux:
    name: Upload Linux Bundles
    needs:
      - build-linux
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Download Bundles
        uses: actions/download-artifact@v3
        with:
          name: linux-bundles
          path: ./bundle
      - name: Upload Typino.deb
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ jobs.release.outputs.upload_url }}
          asset_path: ./bundle/deb/Typino*.app
          asset_name: Typino-${{ steps.version.outputs.prop }}.deb
          asset_content_type: application/gzip
      - name: Upload Typino.AppImage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ jobs.release.outputs.upload_url }}
          asset_path: ./bundle/appimage/Typino*.AppImage
          asset_name: Typino-${{ steps.version.outputs.prop }}.AppImage
          asset_content_type: application/gzip

  release-assets-windows:
    name: Upload Windows Bundles
    needs:
      - build-windows
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - name: Download Bundles
        uses: actions/download-artifact@v3
        with:
          name: window-bundles
          path: ./bundle
      - name: Upload Typino.msi
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ jobs.release.outputs.upload_url }}
          asset_path: ./bundle/Typino*.msi
          asset_name: Typino-${{ steps.version.outputs.prop }}.msi
          asset_content_type: application/gzip
